# Generated by Django 3.1.7 on 2021-03-17 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ensembl.production.djcore.models
import ensembl.production.masterdb.fields
import jsonfield.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAttribType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('attrib_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', ensembl.production.djcore.models.NullTextField(blank=True, null=True)),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterattribtype_created_by', related_query_name='masterattribtype_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterattribtype_modified_by', related_query_name='masterattribtype_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AttribType',
                'db_table': 'master_attrib_type',
            },
            bases=(models.Model, ensembl.production.djcore.models.HasDescription),
        ),
        migrations.CreateModel(
            name='WebData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('web_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField(null=True)),
                ('comment', ensembl.production.djcore.models.NullTextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='webdata_created_by', related_query_name='webdata_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='webdata_modified_by', related_query_name='webdata_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebData',
                'db_table': 'web_data',
            },
            bases=(models.Model, ensembl.production.djcore.models.HasDescription),
        ),
        migrations.CreateModel(
            name='MasterUnmappedReason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('unmapped_reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary_description', models.CharField(blank=True, max_length=255, null=True)),
                ('full_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterunmappedreason_created_by', related_query_name='masterunmappedreason_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterunmappedreason_modified_by', related_query_name='masterunmappedreason_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_unmapped_reason',
            },
        ),
        migrations.CreateModel(
            name='MasterMiscSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('misc_set_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('max_length', models.PositiveIntegerField()),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mastermiscset_created_by', related_query_name='mastermiscset_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mastermiscset_modified_by', related_query_name='mastermiscset_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'master_misc_set',
            },
            bases=(models.Model, ensembl.production.djcore.models.HasDescription),
        ),
        migrations.CreateModel(
            name='MasterAttrib',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('attrib_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=80)),
                ('attrib_type', models.ForeignKey(db_column='attrib_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensembl_production_db.masterattribtype')),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterattrib_created_by', related_query_name='masterattrib_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterattrib_modified_by', related_query_name='masterattrib_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attrib',
                'db_table': 'master_attrib',
                'unique_together': {('attrib_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisDescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('analysis_description_id', models.AutoField(primary_key=True, serialize=False)),
                ('logic_name', models.CharField(max_length=128, unique=True)),
                ('description', ensembl.production.djcore.models.NullTextField(blank=True, null=True)),
                ('display_label', models.CharField(max_length=256)),
                ('db_version', models.BooleanField(default=True, verbose_name='Use DB version')),
                ('displayable', models.BooleanField(default=True, verbose_name='Is displayed')),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysisdescription_created_by', related_query_name='analysisdescription_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysisdescription_modified_by', related_query_name='analysisdescription_updates', to=settings.AUTH_USER_MODEL)),
                ('web_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis', to='ensembl_production_db.webdata')),
            ],
            options={
                'db_table': 'analysis_description',
            },
            bases=(models.Model, ensembl.production.djcore.models.HasDescription),
        ),
        migrations.CreateModel(
            name='MetaKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('meta_key_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_optional', models.BooleanField(default=False)),
                ('db_type', multiselectfield.db.fields.MultiSelectField(choices=[('cdna', 'cdna'), ('compara', 'compara'), ('core', 'core'), ('funcgen', 'funcgen'), ('otherfeatures', 'otherfeatures'), ('rnaseq', 'rnaseq'), ('variation', 'variation'), ('vega', 'vega'), ('presite', 'presite'), ('sangervega', 'sangervega')], max_length=80)),
                ('description', ensembl.production.djcore.models.NullTextField(blank=True, null=True)),
                ('is_multi_value', models.BooleanField(default=False)),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='metakey_created_by', related_query_name='metakey_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='metakey_modified_by', related_query_name='metakey_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meta_key',
                'unique_together': {('name', 'is_optional', 'is_current')},
            },
            bases=(models.Model, ensembl.production.djcore.models.HasDescription),
        ),
        migrations.CreateModel(
            name='MasterExternalDb',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('external_db_id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=100)),
                ('db_release', models.CharField(blank=True, max_length=255, null=True)),
                ('status', ensembl.production.masterdb.fields.EnumField(choices=[('KNOWNXREF', 'KNOWNXREF'), ('KNOWN', 'KNOWN'), ('XREF', 'XREF'), ('PRED', 'PRED'), ('ORTH', 'ORTH'), ('PSEUDO', 'PSEUDO')], max_length=256)),
                ('priority', models.IntegerField()),
                ('db_display_name', models.CharField(max_length=255)),
                ('type', ensembl.production.masterdb.fields.EnumField(choices=[('ARRAY', 'ARRAY'), ('ALT_TRANS', 'ALT_TRANS'), ('ALT_GENE', 'ALT_GENE'), ('MISC', 'MISC'), ('LIT', 'LIT'), ('PRIMARY_DB_SYNONYM', 'PRIMARY_DB_SYNONYM'), ('ENSEMBL', 'ENSEMBL')], max_length=256)),
                ('secondary_db_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_db_table', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ensembl.production.djcore.models.NullTextField(blank=True, null=True)),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterexternaldb_created_by', related_query_name='masterexternaldb_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterexternaldb_modified_by', related_query_name='masterexternaldb_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External DB',
                'db_table': 'master_external_db',
                'unique_together': {('db_name', 'db_release', 'is_current')},
            },
            bases=(models.Model, ensembl.production.djcore.models.HasDescription),
        ),
        migrations.CreateModel(
            name='MasterBiotype',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('biotype_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('is_dumped', models.BooleanField(default=True)),
                ('object_type', ensembl.production.masterdb.fields.EnumField(choices=[('gene', 'gene'), ('transcript', 'transcript')], default='gene', max_length=256)),
                ('db_type', multiselectfield.db.fields.MultiSelectField(choices=[('cdna', 'cdna'), ('core', 'core'), ('coreexpressionatlas', 'coreexpressionatlas'), ('coreexpressionest', 'coreexpressionest'), ('coreexpressiongnf', 'coreexpressiongnf'), ('funcgen', 'funcgen'), ('otherfeatures', 'otherfeatures'), ('rnaseq', 'rnaseq'), ('variation', 'variation'), ('vega', 'vega'), ('presite', 'presite'), ('sangervega', 'sangervega')], default='core', max_length=128)),
                ('description', ensembl.production.djcore.models.NullTextField(blank=True, null=True)),
                ('biotype_group', ensembl.production.masterdb.fields.EnumField(choices=[('coding', 'coding'), ('pseudogene', 'pseudogene'), ('snoncoding', 'snoncoding'), ('lnoncoding', 'lnoncoding'), ('mnoncoding', 'mnoncoding'), ('LRG', 'LRG'), ('undefined', 'undefined'), ('no_group', 'no_group')], default='no_group', max_length=256)),
                ('so_acc', models.CharField(blank=True, max_length=64, null=True)),
                ('so_term', models.CharField(blank=True, max_length=1023, null=True)),
                ('attrib_type', models.ForeignKey(blank=True, db_column='attrib_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ensembl_production_db.masterattribtype')),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterbiotype_created_by', related_query_name='masterbiotype_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterbiotype_modified_by', related_query_name='masterbiotype_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biotype',
                'db_table': 'master_biotype',
                'unique_together': {('name', 'object_type')},
            },
            bases=(models.Model, ensembl.production.djcore.models.HasDescription),
        ),
        migrations.CreateModel(
            name='MasterAttribSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created on')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Update')),
                ('is_current', models.BooleanField(default=True)),
                ('attrib_set_id', models.IntegerField()),
                ('attrib', models.OneToOneField(db_column='attrib_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='related_attrib_set', serialize=False, to='ensembl_production_db.masterattrib')),
                ('created_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='created_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterattribset_created_by', related_query_name='masterattribset_creates', to=settings.AUTH_USER_MODEL)),
                ('modified_by', ensembl.production.djcore.models.SpanningForeignKey(blank=True, db_column='modified_by', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterattribset_modified_by', related_query_name='masterattribset_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AttribSet',
                'db_table': 'master_attrib_set',
                'unique_together': {('attrib_set_id', 'attrib')},
            },
        ),
    ]
