# Generated by Django 3.2.19 on 2023-11-16 16:09

from django.db import migrations, models
import ensembl.production.djcore.models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metakey',
            name='example',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='metakey',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mastermiscset',
            name='description',
            field=ensembl.production.djcore.models.NullTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
