# Generated by Django 3.2.19 on 2023-12-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0002_auto_20231116_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='metakey',
            name='target_site',
            field=models.CharField(choices=[('Main', 'main'), ('New Web', 'new')], default='main',
                                   help_text='If mandatory only, tells which target site meta_key is mandatory for',
                                   max_length=127),
        ),
    ]
