# Generated by Django 3.2.19 on 2023-12-11 11:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ensembl_production_db', '0003_metakey_target_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metakey',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='By Default meta key are mandatory, check this if not'),
        ),
        migrations.AlterField(
            model_name='metakey',
            name='target_site',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', 'Main ensembl Web'), ('new', 'New Website')], default='main', help_text='If mandatory only, tells which target site meta_key is mandatory for', max_length=127),
        ),
    ]
